-- AlterTable
ALTER TABLE "MyRequest" ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TEXT,
ALTER COLUMN "finishedAt" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Request" ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TEXT,
ALTER COLUMN "finishedAt" SET DATA TYPE TEXT;
